name: Sync Laravel Project Files

on:
  push:
    branches:
      - main

jobs:
  file-sync:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          state-name: .ftp-deploy-sync-state.json
