jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: 'https://appd.aneramedia.com'
          repository_root: '/home/anet4435/public_html/appd.aneramedia.com'
          branch: main
          cpanel_token: '${{ secrets.CPANEL_TOKEN }}'
          
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"
