name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v4 # Ensure you have the latest code

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, bcmath, curl

      - name: Install Composer
        run: sudo apt-get install composer

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Sync files to cPanel
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.CPANEL_USERNAME }}
          REMOTE_PORT: 2223
          SOURCE: "."
          TARGET: "/home/anet4435/public_html/appd.aneramedia.com"
          # SCRIPT_BEFORE: |
          #   whoami
          #   ls -al
          # SCRIPT_AFTER: |
          #   whoami
          #   ls -al
          #   echo $RSYNC_STDOUT

          # state-name: '.ftp-deploy-sync-state.json'

      # - name: Clear cache (optional)
      #   run: php artisan cache:clear
