name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v3  # You can keep using this; GitHub will handle Node.js 20 transition

      - name: Set up PHP
        uses: shivammathur/setup-php@v2  # Set up the PHP version
        with:
          php-version: '8.1'  # Ensure you are running PHP 8.1+ if using `readonly`
          extensions: mbstring, intl, bcmath, curl

      - name: Install Composer
        run: sudo apt-get install composer

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs

      - name: Generate key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Clear cache (optional)
        run: php artisan cache:clear
