name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: A Laravel deploy action example
    steps:
      - name: Upload from public_html via FTP
        uses: yankewei/laravel-deploy-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          app_env_data: ${{ secrets.ENV_DATA }}
